#!/bin/sh

set -e

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER <<-EOSQL
    ALTER ROLE $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
    CREATE DATABASE pongbsd;
    GRANT ALL PRIVILEGES ON pongbsd TO $POSTGRES_USER;
EOSQL